services:
  - type: web
    name: django-web
    env: python
    buildCommand: |
      cd mbust_project
      pip install -r requirements.txt
    startCommand: gunicorn mbust_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mbust_project.settings
      - key: DATABASE_URL
        fromDatabase:
          name: mbust_iot
          property: connectionString
