# Generated by Django 3.2.8 on 2025-06-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('certification', models.CharField(choices=[('organic', 'Organic'), ('safe_food', 'Safe Food')], max_length=50)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
