# Generated by Django 3.2.8 on 2025-06-03 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='produces', to='admin_auth.user'),
            preserve_default=False,
        ),
    ]
