# Generated by Django 3.2.8 on 2025-06-04 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0005_vegetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce_items', to='admin_auth.vegetable'),
        ),
    ]
