# Generated by Django 3.2.8 on 2025-06-15 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0009_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
