# Generated by Django 3.2.8 on 2025-06-17 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0012_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produce',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
