# Generated by Django 5.2.3 on 2025-06-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0014_temperaturereading'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturereading',
            name='humidity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperaturereading',
            name='light',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
